
-- ID
-- S11219545 Shamal Prasad
-- S11220337 George Fong
-- S11215227 Daniyal Sultan
-- S11219345 Akash Mishra


-- create table structure
-- https://genesis.usp.ac.fj/phpmyadmin/
-- The indexes

-- Table structure for 'COMPANY'
DROP TABLE IF EXISTS COMPANY;
CREATE TABLE IF NOT EXISTS COMPANY (
    COMP_CODE INT(11) NOT NULL DEFAULT 0,
    COMP_NAME VARCHAR(25) DEFAULT NULL,
    CONSTRAINT COMP_PK_CCODE PRIMARY KEY (COMP_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- Table structure for 'QUALIFICATION'
DROP TABLE IF EXISTS QUALIFICATION;
CREATE TABLE IF NOT EXISTS QUALIFICATION (
    QUAL_CODE INT(11) NOT NULL DEFAULT 0,
    QUAL_DESCRIPTION VARCHAR(255) DEFAULT NULL,
    CONSTRAINT QUAL_PK_QCODE PRIMARY KEY (QUAL_CODE),
    INDEX QUAL_IDX_DESC (QUAL_DESCRIPTION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- Table structure for 'CANDIDATE'
DROP TABLE IF EXISTS CANDIDATE;
CREATE TABLE IF NOT EXISTS CANDIDATE (
    CAND_NUM INT(11) NOT NULL DEFAULT 0,
    CAND_LNAME VARCHAR(15) DEFAULT NULL,
    CONSTRAINT CANDIDATE_PK_CANDNUM PRIMARY KEY (CAND_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for 'EDUCATION'
DROP TABLE IF EXISTS EDUCATION;
CREATE TABLE IF NOT EXISTS EDUCATION (
    QUAL_CODE INT(11) NOT NULL DEFAULT 0,
    CAND_NUM INT(11) NOT NULL DEFAULT 0,
    EDUC_DATE DATE DEFAULT NULL,
    CONSTRAINT EDU_PK_QCODE_CANDNUM PRIMARY KEY (QUAL_CODE, CAND_NUM),
    CONSTRAINT EDU_FK_CANDNUM FOREIGN KEY (CAND_NUM) REFERENCES CANDIDATE (CAND_NUM),
    CONSTRAINT EDU_FK_QCODE FOREIGN KEY (QUAL_CODE) REFERENCES QUALIFICATION (QUAL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for 'OPENING'
DROP TABLE IF EXISTS OPENING;
CREATE TABLE IF NOT EXISTS OPENING (
    OPENING_NUM INT(11) NOT NULL DEFAULT 0,
    OPENING_DESCRIPTION VARCHAR(255) DEFAULT NULL,
    OPENING_AVAILABLE INT(11) DEFAULT NULL,
    COMP_CODE INT(11) DEFAULT NULL,
    QUAL_CODE INT(11) DEFAULT NULL,
    CONSTRAINT OPENING_PK_COURSECODE PRIMARY KEY (OPENING_NUM),
    CONSTRAINT OPENING_FK_COMPCODE FOREIGN KEY (COMP_CODE) REFERENCES COMPANY (COMP_CODE),
    CONSTRAINT OPENING_FK_QCODE FOREIGN KEY (QUAL_CODE) REFERENCES QUALIFICATION (QUAL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for 'COURSE'
DROP TABLE IF EXISTS COURSE;
CREATE TABLE IF NOT EXISTS COURSE (
    COURSE_NUM INT(11) NOT NULL DEFAULT 0,
    COURSE_DESCRIPTION VARCHAR(255) DEFAULT NULL,
    COURSE_FEE DECIMAL(10, 2) DEFAULT 0.00,
    QUAL_CODE INT(11) DEFAULT NULL,
    CONSTRAINT COURSE_PK_COURSENUM PRIMARY KEY (COURSE_NUM),
    CONSTRAINT COURSE_FK_QCODE FOREIGN KEY (QUAL_CODE) REFERENCES QUALIFICATION (QUAL_CODE),
    INDEX COURSE_IDX_CDES (COURSE_DESCRIPTION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for 'PREREQUISITE'
DROP TABLE IF EXISTS PREREQUISITE;
CREATE TABLE IF NOT EXISTS PREREQUISITE (
    COURSE_NUM INT(11) NOT NULL DEFAULT 0,
    QUAL_CODE INT(11) NOT NULL DEFAULT 0,
    CONSTRAINT PREREQUISITE_PK_COURSENUM_QCODE PRIMARY KEY (COURSE_NUM, QUAL_CODE),
    CONSTRAINT PREREQUISITE_FK_COURSENUM FOREIGN KEY (COURSE_NUM) REFERENCES COURSE (COURSE_NUM),
    CONSTRAINT PREREQUISITE_FK_QCODE FOREIGN KEY (QUAL_CODE) REFERENCES QUALIFICATION (QUAL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for 'SESSION'
DROP TABLE IF EXISTS SESSION;
CREATE TABLE IF NOT EXISTS SESSION (
    SESSION_NUM INT(11) NOT NULL DEFAULT 0,
    SESSION_STARTDATE DATE DEFAULT NULL,
    SESSION_FEE DECIMAL(10, 2) DEFAULT 0.00,
    COURSE_NUM INT(11) DEFAULT NULL,
    CONSTRAINT SESSION_PK_SNUM PRIMARY KEY (SESSION_NUM),
    CONSTRAINT SESSION_FK_COURSENUM FOREIGN KEY (COURSE_NUM) REFERENCES COURSE (COURSE_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for 'ENROLL'
DROP TABLE IF EXISTS ENROLL;
CREATE TABLE IF NOT EXISTS ENROLL (
    SESSION_NUM INT(11) NOT NULL DEFAULT 0,
    CAND_NUM INT(11) NOT NULL DEFAULT 0,
    ENROLL_DATE DATE DEFAULT NULL,
    ENROLL_FEEPAID DECIMAL(10, 2) DEFAULT 0.00,
    CONSTRAINT ENROLL_PK_SNUM_CANDNUM PRIMARY KEY (SESSION_NUM, CAND_NUM),
    CONSTRAINT ENROLL_FK_SNUM FOREIGN KEY (SESSION_NUM) REFERENCES SESSION (SESSION_NUM),
    CONSTRAINT ENROLL_FK_CANDNUM FOREIGN KEY (CAND_NUM) REFERENCES CANDIDATE (CAND_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for 'PLACEMENT'
DROP TABLE IF EXISTS PLACEMENT;
CREATE TABLE IF NOT EXISTS PLACEMENT(
    PLACEMENT_NUM INT(11) NOT NULL DEFAULT 0,
    PLACEMENT_DATE DATE DEFAULT NULL,
    OPENING_NUM INT(11) DEFAULT NULL,
    CAND_NUM INT(11) DEFAULT NULL,
    PLACEMENT_TOTALHOURS INT(11) DEFAULT NULL,
    CONSTRAINT PLACEMENT_PK_PNUM PRIMARY KEY (PLACEMENT_NUM),
    CONSTRAINT PLACEMENT_FK_CANDNUM FOREIGN KEY (CAND_NUM) REFERENCES CANDIDATE (CAND_NUM),
    CONSTRAINT PLACEMENT_FK_ONUM FOREIGN KEY (OPENING_NUM) REFERENCES OPENING (OPENING_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Table structure for 'JOB_HISTORY'
DROP TABLE IF EXISTS JOB_HISTORY;
CREATE TABLE IF NOT EXISTS JOB_HISTORY (
    JH_ID INT(11) NOT NULL DEFAULT 0,
    CAND_NUM INT(11) DEFAULT NULL,
    PLACEMENT_NUM INT(11) DEFAULT NULL,
    CONSTRAINT JH_PK_ID PRIMARY KEY (JH_ID),
    CONSTRAINT JH_FK_CANDNUM FOREIGN KEY (CAND_NUM) REFERENCES CANDIDATE (CAND_NUM),
    CONSTRAINT JH_FK_PNUM FOREIGN KEY (PLACEMENT_NUM) REFERENCES PLACEMENT (PLACEMENT_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
